# Info for pixi-build
[package]
version = "0.1.0"  # see: https://github.com/prefix-dev/pixi/issues/2946

[package.build.backend]
name = "pixi-build-python"
version = "0.4.*"

[package.build.config]
ignore-pypi-mapping = false

[package.host-dependencies]
uv = "*"

[workspace]
preview = ["pixi-build"]
channels = ["conda-forge"]
